### ISSUE TITLE
Support -spec-url

### ISSUE THREAD

**Issue by trnl** [DapperDox/dapperdox#44]
DapperDox supports `-spec-dir`  and `-spec-filename` arguments. To be able load schemas dynamically additional `-spec-url` needs to be supported:

To make it work dapper dox is started with the following parameters:
```
./dapperdox -bind-addr=0.0.0.0:8080 -spec-dir=/spec \
-spec-filename=service1.json \
-spec-filename=service2.json
```

We need to support remote urls, something like:
```
./dapperdox -bind-addr=0.0.0.0:8080 \
-spec-url=http://service1/swagger.json \
-spec-url=http://service2/swagger.json
```

**Comment by zxchris** [comment]
Internally DapperDox accesses files via HTTP, so delegating the serving of specification files to an external service is quite straightforward.

Instead of adding another configuration option, a suggestion would be the following patterns:

```
-spec-filename=specification.json
-spec-filename=file://specification.json
-spec-filename=http://specification.json
-spec-filename=https://specification.json
```
the first two are equivalent.

We will have a look at this shortly (currently looking at an issue serving files on Windows, which is in the same area, so once that is done....)

**Comment by trnl** [comment]
@zxchris, thanks for feedback. I think we will submit a PR )

**Comment by akobyakov** [comment]
Hi, @zxchris. I've proposed a PR, could you please have a look? The logic looks straightforward, so I just want to be sure I'm not missing anything.

**Comment by osigida** [comment]
Hi @zxchris is there any plans to release fixes?
