### ISSUE TITLE
API spec endpoints with same summary break the UI

### ISSUE THREAD

**Issue by ian-kent** [DapperDox/dapperdox#49]
Having multiple endpoints with the same summary causes one to be overwritten by the other (e.g., for our API, both `/a/1/b/2` and `/b/2/a/1` are effectively the same resource)

More info at ONSdigital/dp-apipoc-server#1

**Comment by zxchris** [comment]
DapperDox names operations / endpoints by using the first value it finds descending the following list:
1. `x-operationName`
2. Operation `summary`
3. Operation method name (`get`, `post`, `put` etc)

From what you've said, I guess you just want to **explicitly** name the endpoint with `x-operationName` if you want the summary to be the same for both?

The name used in the navigation menu is *slightly* different. Dapperdox uses` x-operationName` if defined, otherwise method name. However, if you specify `x-navigateMethodsByName` then you force DapperDox to use the `summary` member.

See [Controlling method names](http://dapperdox.io/docs/spec-method-names ) for details.
