### ISSUE TITLE
Random sorting of operations on summary pages

### ISSUE THREAD

**Issue by bircow** [DapperDox/dapperdox#52]
Operations listed at "summary" pages obviously don't respect ordering in JSON source. Each time I re-run `dopperdox` I see different order of operations. This is pretty inconvenient.

**Comment by zxchris** [comment]
Yes, that will be inconvenient!
The intention was for these to be ordered alphabetically, so that they are consistent. Ideally, I would like them to maintain the order in the specification but, alas, they're defined as a map in the JSON spec, not an array, so ordering can't be guaranteed. We found forcing alphabetical ordering for such things looks "right" to the reader.

However, this seems to have been overlooked (or broken!) on the summary pages.

Thanks for the report.
Will fix!

**Comment by bircow** [comment]
Thanks for your interest! Yes, that's a pitty that's JSON object with not guaraned ordering, not list.

But as ideal I consider adding another `x-` extension to Swagger file. Good name IMHO would be `x-sortOrder` to be consistent with `SortOrder` metadata with identical semantics - value coud be alphanumeric string however usually users will pick numeric values (where smaller number means bigger priority).

Alphabetically sorting would be a "fallback" if `x-sortOrder` is missing.

I also think how to handle if some operations have `x-sortOrder` and some miss it...  How do you handle with it in the case of `SortOrder`? Again, let's implement it with identical behaviour.

**Comment by zxchris** [comment]
We're looking at this at the moment and would appreciate any feedback you may have on our comments/suggestions on pull-request #68 before we implement (or merge) a solution.

**Comment by Kerzman** [comment]
Hey, we are facing the same issue,
any news about this PR?

**Comment by zxchris** [comment]
We've implemented this in version 1.2.0. See [controlling method order](http://dapperdox.io/docs/spec-method-order)
