### ISSUE TITLE
What syntax is [: :]?

### ISSUE THREAD

**Issue by tlkiong** [DapperDox/dapperdox#54]
I have just started using dapperdox and have never written Go. 
Furthermore, I have never seen the syntax `[: :]` before. It would be great to have an overview of the kind of properties / control structures (if...else, for-loops, etc) that is available so that I can best make use of them when creating my own template.

**Comment by zxchris** [comment]
No problem!

DapperDox uses standard [Golang templates](https://golang.org/pkg/text/template/), the only difference is that the escaping in DapperDox templates uses `[:` and `:]` instead of `{{` and `}}`.

The reasons for the syntax change is because of a conflict with `{{` in the early days while DapperDox was part of a different project...

**Comment by tlkiong** [comment]
Thanks a lot @zxchris !
